/**
 * The CryptographicMultiplexer Hub (The Circuit)
 * RFC-001 Section 2.1 - The Spine connecting all Processors concurrently.
 * Re-built to strictly respect pure AsyncIterables and Zero-Trust validation.
 */
import { createHash } from "node:crypto";
import type { BaseEvent, CommittedEvent } from "../interfaces/event.js";
import { AsyncEventQueue } from "./event-queue.js";

function sha256(data: string): string {
    return createHash("sha256").update(data).digest("hex");
}

export class MultiplexerHub {
    private readonly queues = new Set<AsyncEventQueue>();
    private sequenceCounter = 0;
    // Fallback hash logic: Start with a zero-state root if ledger is brand new.
    private lastHash: string = "0000000000000000000000000000000000000000000000000000000000000000";

    public mode: "LiveMode" | "ReplayMode" | "SilentMode" = "LiveMode";

    /**
     * Used *only* by the Bootstrapper during hydration to set the initial hash
     * state before allowing new live events to be broadcast.
     */
    public overrideLedgerState(sequence: number, hash: string) {
        this.sequenceCounter = sequence;
        this.lastHash = hash;
    }

    /**
     * Processors subscribe to the Hub by requesting a dedicated queue.
     * Hub does NOT know who the processors are or how to call them.
     */
    public subscribe(): AsyncIterable<CommittedEvent> {
        const queue = new AsyncEventQueue(256);
        this.queues.add(queue);

        // Attach cleanup logic if the consumer aborts/breaks the loop
        const iterable = queue[Symbol.asyncIterator]();
        const originalReturn = iterable.return?.bind(iterable);

        iterable.return = async (value) => {
            this.queues.delete(queue);
            if (originalReturn) {
                return originalReturn(value);
            }
            return { done: true, value };
        };

        return queue;
    }

    /**
     * Takes a raw BaseEvent generated by a processor, assigns it its immutable 
     * sequence and cryptographic hash, freezes it, and broadcasts it.
     */
    public broadcast(baseEvent: BaseEvent): void {
        const seq = this.sequenceCounter++;
        const prev = this.lastHash;

        // Hash definition per RFC 4.1
        // SHA-256(prevHash + authorId + sequenceNumber + JSON.stringify(payload))
        const rawPayload = JSON.stringify(baseEvent.payload);
        const hashTarget = `${prev}${baseEvent.authorId}${seq}${rawPayload}`;
        const hash = sha256(hashTarget);

        this.lastHash = hash;

        // Convert drafted volatility into finalized volatility
        const volatility = baseEvent.volatility === "durable-draft" ? "durable" : "volatile";

        const committed: CommittedEvent = {
            eventId: crypto.randomUUID(), // Node 19+ global native
            type: baseEvent.type,
            payload: baseEvent.payload,
            authorId: baseEvent.authorId,
            timestamp: baseEvent.timestamp,
            sequenceNumber: seq,
            prevHash: prev,
            hash: hash,
            volatility: volatility,
        };

        // Immutability is Law (RFC 1.2.3)
        Object.freeze(committed);
        Object.freeze(committed.payload);

        // Fan-out to all subscribed queues
        for (const queue of this.queues) {
            queue.push(committed);
        }
    }

    /**
     * Gracefully shuts down the Hub, terminating all active subscriptions
     * to prevent deadlocks in async iterables.
     */
    public close(): void {
        for (const queue of this.queues) {
            queue.close();
        }
        this.queues.clear();
    }

    /**
     * Bypasses cryptographic generation; re-injects historical literal events.
     * Only the bootstrapper should call this during hydration.
     */
    public injectReplay(historicalEvent: CommittedEvent): void {
        // Fan-out to all subscribed queues, flagged as replay
        for (const queue of this.queues) {
            queue.push({
                ...historicalEvent,
                isReplay: true
            });
        }

        // Update internal state trackers so that when it flips to LiveMode, 
        // the next new broadcast continues seamlessly from the end of history.
        this.sequenceCounter = Math.max(this.sequenceCounter, historicalEvent.sequenceNumber + 1);
        this.lastHash = historicalEvent.hash;
    }
}
